using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArtiConnect.Api.Modals
{
    public class AyarResponseModel
    {
        public int Id { get; set; }
        public bool MasaBirlestirildigindeBilgiFisiYazdir { get; set; }
        public bool KritikStoktaUyar { get; set; }
        public bool KisiSayisiGirmekZorunlu { get; set; }
        public bool MasaTasindigindaBilgiFisiYazdir { get; set; }
        public bool UrunSilindigindeBilgiFisiYazdir { get; set; }
        public bool NakitOdemedeParaUstuEkraniOtomatikAcilsin { get; set; }
        public bool MasaSatisEkranindaTeraziyiGoster { get; set; }
        public bool HizliSatisEkranindaTeraziyiGoster { get; set; }
        public bool PaketSiparisEkranindaTeraziyiGoster { get; set; }
        public bool MasaSatisEkranindaBarkoduGoster { get; set; }
        public bool HizliSatisEkranindaBarkoduGoster { get; set; }
        public bool PaketSiparisEkranindaBarkoduGoster { get; set; }
        public bool EklenenUrununAdiniGoster { get; set; }
        public string YedeklemeDizini { get; set; }
        public string AdisyonYazdirma { get; set; }
        public float GarsoniyeYuzdesi { get; set; }
        public string AcilisEkrani { get; set; }
        public string YoneticiSifresi { get; set; }
        public string Dil { get; set; }
        public int UrunGrubuGenisligi { get; set; }
        public int UrunGrubuYuksekligi { get; set; }
        public int UrunGrubuResmiGenisligi { get; set; }
        public int UrunGrubuResmiYuksekligi { get; set; }
        public int UrunGrubuFontu { get; set; }
        public int UrunGenisligi { get; set; }
        public int UrunYuksekligi { get; set; }
        public int UrunResmiGenisligi { get; set; }
        public int UrunResmiYuksekligi { get; set; }
        public int UrunFontu { get; set; }
        public string UrunNotuYaziciAdi { get; set; }
        public bool HizliSatistaSiparisFisiYazdir { get; set; }
        public float UrunGrubuListelenecekSatir { get; set; }
        public bool HizliUrunKayitEkrani { get; set; }
        public byte[] FirmaResmi { get; set; }
        public bool UrunNotuYazdir { get; set; }
        public bool FavoriUrunGrubu { get; set; }
        public bool CallerId { get; set; }
        public float SlaytGecisSuresi { get; set; }
        public string SecilenSatirBackColor { get; set; }
        public string EskiSiparisBackColor { get; set; }
        public string YeniSiparisBackColor { get; set; }
        public string DoluMasaRengi { get; set; }
        public string AdisyonuYazdirilanMasaRengi { get; set; }
        public string SmsRaporTelefonNumarasi { get; set; }
        public string MailRaporMailAdresi { get; set; }
        public bool PaketSiparisKuryeSmsGonder { get; set; }
        public bool PaketSiparisMusteriSmsGonder { get; set; }
        public bool TerazideOnayIste { get; set; }
        public float VarsayılanKartIndirimi { get; set; }
        public string MusteriEkraniYazisi { get; set; }
        public bool GunSonundaSmsGonder { get; set; }
        public string GunSonuTelefon { get; set; }
        public string GunSonuSaat { get; set; }
        public string GunSonuDakika { get; set; }
        public bool SatisEkranindaUrunleriAlfabetikSirala { get; set; }
        public bool EkstraOzellikSecildigindeOtomatikKapat { get; set; }
        public float SalonButonFontu { get; set; }
        public float MasaButonFontu { get; set; }
        public float SalonButonGenisligi { get; set; }
        public float SalonButonYuksekligi { get; set; }
        public float MasaButonGenisligi { get; set; }
        public float MasaButonYuksekligi { get; set; }
        public bool UrunKayittaResimSecildigindeAdiOtomatikGetir { get; set; }
        public bool AltUrunGruplari { get; set; }
        public string UrunGrubuRengi { get; set; }
        public bool SalonlarYetkiyeBagliOlsun { get; set; }
        public bool UrunGruplariYetkiyeBagliOlsun { get; set; }
        public bool CariSatistaSmsGonder { get; set; }
        public bool CariOdemedeSmsGonder { get; set; }
        public bool CokluGirisKisitlamasi { get; set; }
        public bool CokluMasaIslemKisitlamasi { get; set; }
        public bool PaketSiparisteOtomatikAdisyonYazdir { get; set; }
        public string IpAdresi { get; set; }
        public bool SonTuketimTarihiniKullan { get; set; }
        public float SonTuketimTarihiGunSayisi { get; set; }
        public float AlisFiyatHesaplamaYuzdesi { get; set; }
        public bool MasaGostergeEkrani { get; set; }
        public int MasaGostergeEkraniMonitorNo { get; set; }
        public bool MusteriEkraniAktif { get; set; }
        public int MusteriEkraniEkranNo { get; set; }
        public string SmsOrijinator { get; set; }
        public string SmsKullaniciAdi { get; set; }
        public string SmsBayi { get; set; }
        public string SmsSifre { get; set; }
        public float SatisGruplarindaListelenecekUrunSayisi { get; set; }
        public bool ParaUstuEkranindaNumaratorKullan { get; set; }
        public bool FullModul { get; set; }
        public bool MasaVeHizliSatisModulu { get; set; }
        public bool HizliSatisModulu { get; set; }
        public bool Laundry { get; set; }
        public bool AdisyondaDovizToplamlariniGoser { get; set; }
        public bool AdisyonKapatmadaUyar { get; set; }
        public bool UrunGruplarindaBardakBoyuKullan { get; set; }
        public bool HizliSatisVePaketSiparisModulu { get; set; }
        public bool TeraziEkraniniKullan { get; set; }
        public string YemekSepetiKullaniciAdi { get; set; }
        public string YemekSepetiSifre { get; set; }
        public string GetirKullaniciAdi { get; set; }
        public string GetirSifre { get; set; }
        public string TrendyolKullaniciAdi { get; set; }
        public string TrendyolSifre { get; set; }
        public string MigrosKullaniciAdi { get; set; }
        public string MigrosSifre { get; set; }
        public bool SiparisiOtomatikOnayla { get; set; }
        public int TeslimatSuresi { get; set; }
        public bool PaketSiparisteKargoButonuGorunsun { get; set; }
        public bool Kozmetik { get; set; }
        public bool HizliSatistaOdemeButonlariniBuyut { get; set; }
        public bool TeraziHizliSatisiniKullan { get; set; }
        public string BekletButon7Adi { get; set; }
        public string BekletButon8Adi { get; set; }
        public string BekletButon9Adi { get; set; }
        public string BekletButon10Adi { get; set; }
        public string BekletButon11Adi { get; set; }
        public string BekletButon12Adi { get; set; }
        public bool AktifSatis { get; set; }
        public string SmsAltBilgisi { get; set; }
        public int KullanilanSms { get; set; }
        public string TeraziTanimKodlari { get; set; }
        public bool HizliUrunBulButonu { get; set; }
        public bool DigiRm5900Kullan { get; set; }
        public float TeraziGramajPayi { get; set; }
        public string EdmKullaniciAdi { get; set; }
        public string EdmSifre { get; set; }
        public string EdmVkn { get; set; }
        public string EdmSonKayitNo { get; set; }
        public bool IkinciHizliSatisEkraniniKullan { get; set; }
        public int EIrsaliyeKopyaSayisi { get; set; }
        public bool CariBakiyedeUrunGuncelFiyatiniKullan { get; set; }
        public float StokGirisindeAlinacakDara { get; set; }
        public bool AdisyondaKdvOranlariniGetir { get; set; }
        public bool UcuncuFiyatiKullan { get; set; }
        public bool TeraziMiktari0IseMiktariManuelGir { get; set; }
        public bool TeraziMiktari0IseUrunEklemeyiEngelle { get; set; }
        public DateTime KayitTarihi { get; set; }
        public DateTime? GuncellemeTarihi { get; set; }
        public DateTime? SilmeTarihi { get; set; }
        public int Durum { get; set; }
        public string Kod { get; set; }
        public bool YeniliklerdenHaberdarOl { get; set; }
        public bool ElTerminaliAktif { get; set; }
        public bool InposAktif { get; set; }
        public string InposSeriNo { get; set; }
        public bool SatisTablosundaKdvAyrımlarınıGoster { get; set; }
        public bool Butik { get; set; }
        public bool VadeTarihiUyarisi { get; set; }
        public bool KrediKartiIleSatis { get; set; }
        public bool IlkUrunGrubuOtomatikGelsin { get; set; }
        public bool SatisEkranindaDövizTutarlariniGoster { get; set; }
        public float EtiketteFiyataEklenecekYüzde { get; set; }
        public bool AdisyondaPersoneliKaldir { get; set; }
        public bool MusteriEkranindaResmiGizle { get; set; }
        public bool HizliSatisVeTeknikServis { get; set; }
        public bool LogoAktariminiKullan { get; set; }
        public bool StokGirisindeUrunuOtomatikEkle { get; set; }
        public bool IkinciFiyatiKullan { get; set; }
        public bool AdisyonYazdirmadaYaziciSec { get; set; }
        public bool SatisEkraniniTersineCevir { get; set; }
        public float ElTerminaliSatirSayisi { get; set; }
        public string Ticari1KullaniciAdi { get; set; }
        public string Ticari1Sifre { get; set; }
        public string Ticari1Vkn { get; set; }
        public int Ticari1KullaniciNo { get; set; }
        public bool DovizliSatis { get; set; }
        public bool UrunGruplariniSayfalaraAyir { get; set; }
        public bool KitchenAyarlamasi { get; set; }
        public bool UrunGruplariniDikeyListele { get; set; }
        public bool UrunlerdeFiyatiGoster { get; set; }
        public bool SatisEkranindaNumaratoruGoster { get; set; }
        public float AdisyonDetayFontBuyuklugu { get; set; }
        public bool ManuelKurGirisi { get; set; }
        public float DolarKurOrani { get; set; }
        public float EuroKurOrani { get; set; }
        public float PoundKurOrani { get; set; }
        public bool HizliSatistaSatirdanFiyatDegistirme { get; set; }
        public bool AdisyonuGruplaraAyir { get; set; }
        public bool KartliSatis { get; set; }
        public string BekletButon1Adi { get; set; }
        public string BekletButon2Adi { get; set; }
        public string BekletButon3Adi { get; set; }
        public string BekletButon4Adi { get; set; }
        public string BekletButon5Adi { get; set; }
        public string BekletButon6Adi { get; set; }
        public string Ticari1SubeNo { get; set; }
        public bool IkramiyeSatisi { get; set; }
        public string BulutYedekMailAdresi { get; set; }
        public bool IskontoyuBirimFiyatlaraYansit { get; set; }
        public bool ServisUcretiniTutarOlarakGir { get; set; }
        public bool SatisEkranindaSaatGoster { get; set; }
        public bool EftOdemeTusuAktif { get; set; }
        public byte[] QrMenuFirmaLogosu { get; set; }
        public string FirmaAdresi { get; set; }
        public string FirmaTelefonu { get; set; }
        public string FirmaMailAdresi { get; set; }
        public string FirmaInstagramAdresi { get; set; }
        public string QrMenuFirmaAdi { get; set; }
        public string FirmaFacebookAdresi { get; set; }
        public string FirmaWhatsAppNumarasi { get; set; }
        public string WifiSifresi { get; set; }
        public string FirmaVkn { get; set; }
        public bool TemTeraziKullan { get; set; }
        public bool TeknikServisBayiKullanimi { get; set; }
        public bool ElTerminaliOtomatikBaslat { get; set; }
        public bool ApiOtomatikBaslat { get; set; }
        public bool OtomatikDaraAl { get; set; }
        public float CekilisHakkiSatisTutari { get; set; }
        public bool CariKartliSatis { get; set; }
        public string BayiTelefonNumarasi { get; set; }
        public byte[] BayiResmi { get; set; }
        public bool SecenekVeEkstraOzellikleriOtomatikAcilsin { get; set; }
        public bool TeraziSatisAyari { get; set; }
        public bool AnaNoktaAktarimiAktif { get; set; }
        public string AnaNoktaVeritabani { get; set; }
        public bool GunSonuKasaGirisi { get; set; }
        public bool UrunSilmedeAciklamaZorunluOlsun { get; set; }
        public bool UrunIkramdaAciklamaZorunluOlsun { get; set; }
        public bool AdisyonIptaldeAciklamaZorunluOlsun { get; set; }
        public bool AdisyonIkramdaAciklamaZorunluOlsun { get; set; }
        public bool FiyatDegistirmedeAciklamaZorunluOlsun { get; set; }
        public bool HurdaSatis { get; set; }
        public bool AcilistaAnaNoktadanUrunleriEsle { get; set; }
        public bool SatisEkranindaUrunGruplariniKaldir { get; set; }
        public bool SiparisFisi56MM { get; set; }
        public bool AdisyonFisi56MM { get; set; }
        public bool MasaEkranindaHizliSatisGecisi { get; set; }
        public bool MasaButonlarindaTutariGizle { get; set; }
        public bool MasaButonlarindaSureyiGizle { get; set; }
        public int NakitKisayolTusu { get; set; }
        public int KrediKartiKisayolTusu { get; set; }
        public int CariKisayolTusu { get; set; }
        public int DigerKisayolTusu { get; set; }
        public int KasaAcKisayolTusu { get; set; }
        public int YazdirKisayolTusu { get; set; }
        public int IkinciFiyatKisayolTusu { get; set; }
        public bool UrunEklemedeSesliUyarı { get; set; }
        public int UrunEklemeUyariSesi { get; set; }
        public bool KapanistaYedekAlmaUyarısıVer { get; set; }
        public string HuginCihazSeriNo { get; set; }
        public string HuginIp { get; set; }
        public string HuginPort { get; set; }
        public bool HuginAktif { get; set; }
        public bool UrunIskontoDisiBirakma { get; set; }
        public int SiramatikEkranNo { get; set; }
        public bool SiramatikAktif { get; set; }
        public bool MasaEkranindaSiramatikButonunuGoster { get; set; }
        public bool MasaEkranindaPaketSiparisButonunuGoster { get; set; }
        public bool AcilistaAnaNoktadanKullanicilariEsle { get; set; }
        public string IadeOnayTelefonNumarasi { get; set; }
        public string ZayiOnayTelefonNumarasi { get; set; }
        public string KaporaBilgiTelefonNumarasi { get; set; }
        public bool SatisEkranindaStoklariGoster { get; set; }
        public bool UrunYonetimindeStoklariGoster { get; set; }
        public bool TeknikServisCariBilgisiniGizle { get; set; }
        public bool TeknikServisFaturaOlusturmaSorgusunuKaldir { get; set; }
        public string IkramOnayTelefonNumarasi { get; set; }
        public bool TeraziYontem2 { get; set; }
        public bool UrunTablosundaKritikStokKullan { get; set; }
        public bool TeknikServisDepoKullanimi { get; set; }
        public bool MusteriEkranindaAdisyonBilgisiniGizle { get; set; }
        public bool EtiketYazdirBulunanUrunuOtomatikYazdir { get; set; }
        public int OndalikBasamakSayisi { get; set; }
        public bool TeraziEtiketiManuelMiktarGirisi { get; set; }
        public bool QrMenu { get; set; }
        public string Bekletme1Not { get; set; }
        public string Bekletme2Not { get; set; }
        public string Bekletme3Not { get; set; }
        public string Bekletme4Not { get; set; }
        public string Bekletme5Not { get; set; }
        public string Bekletme6Not { get; set; }
        public bool AdisyonIptalBilgiFisiYazdir { get; set; }
        public bool BekletmedenSonraKapat { get; set; }
        public bool BekletButonAdlariKullaniciAdiOlsun { get; set; }
        public string Sirket { get; set; }
    }
}