using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArtiConnect.Integrations.Ingenico
{
    internal enum FunctionFlags
    {
        GMP_EXT_DEVICE_FUNC_BIT_PARAM_YUKLE = 1,
        GMP_EXT_DEVICE_FUNC_BIT_Z_RAPOR,
        GMP_EXT_DEVICE_FUNC_BIT_X_RAPOR,
        GMP_EXT_DEVICE_FUNC_BIT_MALI_RAPOR,
        GMP_EXT_DEVICE_FUNC_BIT_EKU_RAPOR,
        GMP_EXT_DEVICE_FUNC_BIT_MALI_KUMULATIF,
        GMP_EXT_DEVICE_FUNC_BIT_Z_RAPOR_GONDER,
        GMP_EXT_DEVICE_FUNC_BIT_KASIYER_SEC,
        GMP_EXT_DEVICE_FUNC_BIT_KASIYER_LOGOUT,
        GMP_EXT_DEVICE_FUNC_BIT_AVANS,
        GMP_EXT_DEVICE_FUNC_BIT_ODEME,
        GMP_EXT_DEVICE_FUNC_BIT_CEKMECE_ACMA,
        GMP_EXT_DEVICE_FUNC_READ_CARD,
        GMP_EXT_DEVICE_FUNC_GET_CARD_PUAN,
        GMP_EXT_DEVICE_FUNC_BIT_BANKA_GUN_SONU,
        GMP_EXT_DEVICE_FUNC_BIT_BANKA_PARAM_YUKLE,
        GMP_EXT_DEVICE_FUNC_BANKA_IADE,
        GMP_EXT_DEVICE_FUNC_GET_UNIQUE_ID_LIST,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_SON_FIS_KOPYA,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_SON_KOPYA,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_IKI_Z_ARASI,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_IKI_TARIH_ARASI,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_FISTEN_FISE,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_Z_KOPYA,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_DETAIL,
        GMP_EXT_DEVICE_FUNC_EKU_RAPOR_SUMMARY,
        GMP_EXT_DEVICE_FUNC_CHANGE_RECEIPT_HEADER,
        GMP_EXT_DEVICE_FUNC_BANKA_IPTAL,
        GMP_EXT_DEVICE_FUNC_KASIYER_TANIMLA,
        GMP_EXT_DEVICE_FUNC_TRANS_INQUERY,
        GMP_EXT_DEVICE_FUNC_TRANS_STATUS,
        GMP_EXT_DEVICE_FUNC_CREATE_UNIQUE_ID,
        GMP_EXT_DEVICE_FUNC_LOAD_BACKGROUND_TO_FRONT,
        GMP_EXT_DEVICE_FUNC_LOYALTY_IDENTIFICATION,
        GMP_EXT_DEVICE_FUNC_GET_INVOICE_INFO,
        GMP_EXT_DEVICE_FUNC_PAYMENT_VAS_IPTAL,
        GMP_EXT_DEVICE_FUNC_CHECK_PAYMENT_STATUS,
        GMP_EXT_DEVICE_FUNC_BIT_AYLIK_RAPOR_GONDER
    }
}
